### ISSUE TITLE
Otagowanie projektu dla każdego kolejnego inkrementu

### ISSUE THREAD

**Issue by jantechner** [jantechner/ScenarioQualityChecker#2]
Każdy kolejny zrealizowany element rejestru produktu powinien zostać otagowany na GitHubie. 
Proponuję następującą konwencję:
A.B
A - numer sprintu
B - numer zrealizowanego inkrementu
Numer wersji powinien zostać zaktualizowany w pliku pom.xml

**Comment by S-Maciejewski** [comment]
To ma sens tylko kiedy robimy taski (inkrementy) po kolei, a tak będzie rzadko. To prowadzi do sytuacji: zrobiłem task #4,  ale task #3 jest na później, bo przecież najpierw Maven potem Travis - mamy najpierw wersję 1.4 a potem 1.3

Chyba, że inkrement to nasz milestone i taski taskami, a dopiero po zrobieniu wszystkiego dajemy tag. Ale wtedy mało sensu ma numer sprintu, bo w zasadzie pokrywa się to z milestonem

**Comment by S-Maciejewski** [comment]
No i pamiętajcie, że numery tasków są niezależne od milestonów, więc mielibyśmy wersję np. 1.5 a potem 2.6 itd. 
Te numery mogą być wykorzystane do branchowania, żeby wiadomo było który branch jest od czego. Na przykład branch dla taska #4 to SQC-4

**Comment by S-Maciejewski** [comment]
Po dodaniu dokumentacji i wciągnięciu logowania do pliku można by oznaczyć obecną wersję jakoś sensownie. Zakładam, że zmiana wersji po każdym merge'u to głupi pomysł, raczej aktualizacja wersji po każdym sprincie brzmi sensowniej

**Comment by S-Maciejewski** [comment]
Tagi zrobione
