### ISSUE TITLE
Model klas projektu - diagram UML

### ISSUE THREAD

**Issue by jantechner** [jantechner/ScenarioQualityChecker#32]

**Comment by wakulig2** [comment]
![1](https://user-images.githubusercontent.com/44399122/49383894-18acfa80-f71a-11e8-97bb-100343785650.png)
![package transformer 1](https://user-images.githubusercontent.com/44399122/49383898-18acfa80-f71a-11e8-9f13-916a5c8ae2a3.png)

Oceńcie, czy w ramach tej kwestii to powinno wystarczyć. Jak coś więcej potrzeba, to nie mam pomysłu jak.
