### ISSUE TITLE
Testowanie jednostkowe

### ISSUE THREAD

**Issue by jantechner** [jantechner/ScenarioQualityChecker#33]
2 klasy testujące i 20 metod testujących
Przetestowano przynajmniej 10 wywołań metod z zewnętrznych klas za pomocą 'mock objects'

**Comment by S-Maciejewski** [comment]
Jak byście się wyjątkowo mocno męczyli z testami to napiszcie, sporo razy to robiłem, więc może będę mógł coś pomóc jak gdzieś utkniecie
