### ISSUE TITLE
Przygotowanie szkieletu GUI

### ISSUE THREAD

**Issue by S-Maciejewski** [jantechner/ScenarioQualityChecker#34]

**Comment by S-Maciejewski** [comment]
Potrzebuję jakichś wytycznych co do funkcji programu - czy to ma być po prostu jedna strona inputu - wielkie pole tekstowe i menu funkcji do wywołania i potem zależnie od wywołanej funkcji strona z wynikiem (wynikami)? Jakie funkcje mają się tam znaleźć? Zakładam, że jedynym inputem od usera jest scenariusz, tylko pytanie czy w .jsonie czy wpisywany w jakiś inny ustalony sposób? Co myślicie?

**Comment by jantechner** [comment]
Myślę, że Twój pomysł z chowanym polem tekstowym do wpisywania scenariusza jest super (inputem nie może być JSON, to musi być albo parsowanie zwykłego tekstu, albo ewentualnie jakieś angularowe rozwiązanie z listą list)

**Comment by S-Maciejewski** [comment]
Ok, to będzie takie zwykłe pole tekstowe jak np. do wpisywania body w postmanie. Na chwilę obecną koncepcja jest taka, że outputy też będą w polach tekstowych na głównej stronie - do każdego będzie jakiś przycisk-getter, którego kliknięcie będzie rzucało request z wprowadzonym scenariuszem i rzucało zwrotkę na to pole

**Comment by S-Maciejewski** [comment]
Link do repo w readme, instrukcja uruchomienia w repo frontu, więc uważam szkielet GUI za gotowy - zamykam issue
